services:
  redis:
    image: redis:7-alpine
    container_name: osint_redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: osint_neo4j
    environment:
      NEO4J_AUTH: neo4j/neo4j_pass_2024
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data: